# -*- coding: utf-8 -*-
"""Inheritance Exercise.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LfA6tTg4csR71NCOVHCeOWAM1VZDsKlX
"""

class Person:
  def __init__(self, first, last, idNum):
    self.first = first
    self.last = last
    self.idNum = idNum 
  

class Student(Person):
  def __init__(self, first, last, idNum, scores):
    super().__init__(first, last, idNum)
    self.scores = scores

  def calculate(self):
    total = 0

    for score in self.scores:
      total += score

      avg = total /len(self.scores)
      if 90 <= avg <= 100:
            return 'A'
      elif 80 <= avg < 89:
          return 'B'
      elif 70 <= avg < 79:
          return 'C'
      elif 60 <= avg < 69:
          return 'D'
      else:
          return 'F'
      

#line = input("hi ").split()
first = input("First name: ")
last = input("Last name: ")
idNum = input("Student ID: ")
#numScores = int(input()) # not needed for Python
scores = list( map(int, input('Enter a list grades separated by space:').split()) )
s = Student(first, last, idNum, scores)
print(s.first, s.last,"Student ID,", s.idNum, "You got a", s.calculate())